esphome:
  name: basicretic
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret wifipassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basicretic Fallback Hotspot"
    password: "basicretic"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    id: station1
    name: "Station 1"
    pin:
      number: 14
  - platform: gpio
    id: station2
    name: "Station 2"
    pin:
      number: 12
  - platform: gpio
    id: station3
    name: "Station 3"
    pin:
      number: 5
  - platform: gpio
    id: station4
    name: "Station 4"
    pin:
      number: 4
binary_sensor:
  - platform: gpio
    name: "Retic Light Sensor"
    pin:
      number: 13
      inverted: true
    filters:
      - delayed_on_off: 10s
