#Change these substitution to suit your requirements
substitutions:
  name: "micro-retic" #Name of device on network
  
esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: jimmy.micro_retic
    version: "0.1"

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://jeggleston1981/micro_reticulation/micro.yaml@v1
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "password"

captive_portal:

switch:
  - platform: gpio
    name: "Station 1"
    id: station1
    pin:
      number: 14
      inverted: false
  - platform: gpio
    name: "Station 2"
    id: station2
    pin:
      number: 12
      inverted: false
  - platform: gpio
    name: "Station 3"
    id: station3
    pin:
      number: 5
      inverted: false
  - platform: gpio
    name: "Station 4"
    id: station4
    pin:
      number: 4
      inverted: false
binary_sensor:
  - platform: gpio
    name: "Retic Light Sensor"
    pin:
      number: 13
      inverted: true
    filters:
      - delayed_on_off: 10s
